### ISSUE TITLE
⚠ Leaking sensitive information ⚠

### ISSUE THREAD

**Issue by gabrieldejesus** [phptuts/firebase-sveltekit-recipe-site#4]
Hi @phptuts , I noticed that you make your keys sus tokens available in your project, be careful with that malicious people can use.

[Your archive](https://github.com/phptuts/firebase-sveltekit-recipe-site/blob/ssr-example/src/env.ts)

**Comment by brunos3d** [comment]
It's ok my friend
Thank you for your concern :D

Here is a detailed article about
https://medium.com/@paulbreslin/is-it-safe-to-expose-your-firebase-api-key-to-the-public-7e5bd01e637b
As aways a stackoverflow answer
https://stackoverflow.com/a/37484053

**Comment by gabrieldejesus** [comment]
Thank you @BrunoS3D  for article.

**Comment by phptuts** [comment]
Thank you both!
